name: Tim_eds-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - ipywidgets
  - ipykernel
  - pandas
  - xarray
  - iris
  - cartopy
  - bokeh
  - scikit-learn
  - jupyterlab
  - intake
  - s3fs

